version: '3.8'

services:
  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=${SPLUNK_PASSWORD}
      - DOCKER_USERNAME=${DOCKER_USERNAME}
      - DOCKER_PASSWORD=${DOCKER_PASSWORD}
    ports:
      - "8000:8000" # Splunk Web
      - "8088:8088" # HTTP Event Collector
      - "9997:9997" # Splunk Indexing Port
    volumes:
      - splunk-data:/opt/splunk/var
      - splunk-etc:/opt/splunk/etc
    restart: unless-stopped

  universalforwarder:
    image: splunk/universalforwarder:latest
    container_name: universalforwarder
    environment:
      - SPLUNK_PASSWORD=${FORWARDER_PASSWORD}
      - SPLUNK_START_ARGS=--accept-license
      - DOCKER_USERNAME=${DOCKER_USERNAME}
      - DOCKER_PASSWORD=${DOCKER_PASSWORD}
    volumes:
      - uf-data:/opt/splunkforwarder/var
      - uf-etc:/opt/splunkforwarder/etc
    restart: unless-stopped

volumes:
  splunk-data:
  splunk-etc:
  uf-data:
  uf-etc:
